network = 16

# IP Plan for 10.254.x.y
#
# 10.254.1.x: infrastructure services (not builders)
# 10.254.2.x: macOS builders
#            1 -  10: x86 mac minis running NixOS with macOS in a VM
#           50 -  60: x86 mac minis reserved for ofborg
#          100 - 110: m1 mac minis running macOS on the hardware
# 10.254.3.x: (defunct) NixOS.org hosting infrastructure
# 10.254.4.x: infra team administrator machines, for connecting to the bastion

[hosts.bastion]
# wg won't retry resolution if it fails... so
# hard-code the IP to bastion.nixos.org so we don't lock
# ourselves out.
endpoint = "34.254.208.229"
ip = "10.254.1.1"
port = 51820
publicKey = "nG7I9gegJIynKOZ6tzpvmLdCZ/xScTgRZeFvYLFyil4="

# tombstone: 10.254.1.2 chef
# tomstone: 10.254.1.3 ceres
# tombstone: 10.254.2.1 mac1 (host/guest)
# tombstone: 10.254.2.2 mac2 (host/guest)
# tombstone: 10.254.2.3 mac3 (host/guest)
# tombstone: 10.254.2.4 mac4 (host/guest)
# tombstone: 10.254.2.5 mac5 (host/guest)
# tombstone: 10.254.2.6 mac6 (host/guest)
# tombstone: 10.254.2.7 mac7 (host/guest)
# tombstone: 10.254.2.8 mac8 (host/guest)
# tombstone: 10.254.2.9 mac9 (host/guest)

[hosts.eris]
endpoint = "138.201.32.77"
ip = "10.254.1.4"
port = 51820
publicKey = "H/Y+sbNETKZugxGFbOS0m5BSr28jRDL19U37wEw07D8="

[hosts.rhea]
endpoint = "5.9.122.43"
ip = "10.254.1.5"
port = 51820
publicKey = "eIsaf/JYsxL/G5pCzKo10GeiqgdEwp8v9G4BSUBo3h0="

[hosts.haumea]
endpoint = "46.4.89.205"
ip = "10.254.1.9"
port = 51820
publicKey = "Fb41wGKT1TdC4MG5i2NRx6yduddmqm+N+UOtqtDuBG4="

[hosts.macofborg1]
ip = "10.254.2.51"
publicKey = "RPD07xoZYB3aq9hS4pX+qnCHwSbNunK69HGdf8pRtCQ="

[hosts.mac-m1-1]
ip = "10.254.2.101"
publicKey = "r9EEig5zzGS+MlMqK1jCzXB4Rm11Q/c812i7dxGj8gQ="

[hosts.mac-m1-2]
ip = "10.254.2.102"
publicKey = "J0JajIlwirjrry4QsuVzzyyWSGesQWHk16IR99rcwjY="

[hosts.mac-m1-3]
ip = "10.254.2.103"
publicKey = "E/eHbib8pEnPmT6nWjXlv3H5Ww1DfWxZdbz+Cn+jCX0="

[hosts.mac-m1-4]
ip = "10.254.2.104"
publicKey = "qQ0LO8kU+zFPxCk7JBD9OrfGS3Ryl08ePyF+KQxGl2U="

[hosts.mac-m1-5]
ip = "10.254.2.105"
publicKey = "5VWVUb/fiZmAJqCfqMPH2yIa8xze6hEU11ZKYPOtQyQ="

[hosts.mac-m1-6]
ip = "10.254.2.106"
publicKey = "S20ha1NoMUgR67696vi7hmSdSxK/GJM550S0uR2odlA="

[hosts.webserver]
enpdoint = "54.217.220.47"
ip = "10.254.3.1"
port = 51820
publicKey = "/N5//y0elGZdeekUv+IzKZiZ9wcKSOHc2bHmPU8FaCM="

[hosts.hyperchicken]
# Graham's machine, for administrative access
ip = "10.254.4.1"
port = 51820
publicKey = "sXj7LhGQBczgMhEvLewWgyHsmYMMg88vUsz1rrn7fWM="

[hosts.scruffy]
# Graham's machine, for administrative access
ip = "10.254.4.2"
port = 51820
publicKey = "kamC5o3H6UhrfNZjxU6vqdHi3I1+KDOj9tMeuFjiIyk="

[hosts.hermes-conrad]
# Graham's machine, for administrative access
ip = "10.254.4.3"
port = 51820
publicKey = "CDrCOjn7SH7fSn+xg3R/zkZVvVDORMK8uJJbvQrRaiY="

[hosts.nics22]
# Vladimir's machine (@vcunat), for administrative access
ip = "10.254.4.4"
port = 51820
publicKey = "pH2DCtTti9gbyYZ4jFHnhjwDGlWTGKlJ7HFl9ykYjz8="

[hosts.delroth]
# delroth's machine (@delroth), for administrative access
ip = "10.254.4.5"
port = 51820
publicKey = "1PLQcx+eVLgRwN6e7fim53rHQXB7pjIg6okOe2nFoi8="

[hosts.hexa-helix]
# hexa's machine (@mweinelt), for administrative access
ip = "10.254.4.6"
publicKey = "Aco4hlJFNYtSzZDT6O0TtopnBl76e7aoubI6QygNrGM="

[hosts.hexa-io]
# hexa's machine (@mweinelt), for administrative access
ip = "10.254.4.7"
publicKey = "s2UCtX+NEIkfEcLpgQZImQShABoMX6Xtog7cYtI2x2s="
